id: P0008B700
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: nl
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    7674e8bd333e4f42bada3834c3bb359d:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    61c548547d03472ca5f19ad32eb398a7:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    cc86f739773142dd9ab6f1845e203636:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    2994e29d1aeb4615979f6e03a838e50c:
      title: Verses on the Buddha's Previous Lives
      parent: History
    f5c3e83f1b90478cb849edd9c07f2ac2:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    8dabd2382fd249168fc5cecdd8b5cb7d:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    0395e5d6e5654a14bdb88a50592aa56b:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    d2549dacc4514bf79218885c587810a8:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    1a68cb9f93ae4daa9fd3766f7b993f05:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    5be8844e93b449b188b8fccef26fd869:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    b7c2d14e0d6544a0b22ac772be69fac6:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    6651cf1444504797a80a4603e9a466e4:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    4aa613d4387c4e4f8c706ac4ddff7889:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.227030'
last_modified_at: '2022-03-01T03:05:43.227032'
